language: python
dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

sudo: false

install:
  - pip install coveralls fakeredis redis pytest-cov

script: py.test --cov=rediswrapper

after_success: coveralls
